name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ env.DEPLOYMENT_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Production
          auto_inactive: false

      - name: Trigger Vercel Deploy Hook
        id: deploy
        run: |
          RESPONSE=$(curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}")
          echo "DEPLOYMENT_URL=https://${{ github.event.repository.name }}.vercel.app" >> $GITHUB_ENV

      - name: Update Deployment Status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          environment-url: ${{ env.DEPLOYMENT_URL }}